export const festivals = [
    {
        "id": '1',
        "title": 'UPark 2022',
        "description": 'UPark Festival - це високий рівень артистів і особлива атмосфера, це глядачі, для яких музика - невід\'ємна частина життя.',
        "location": 'Sky Family Park Київ, пр-т Г. Ватутіна, 2Т',
        "price": 'Від 1649 грн.',
        "startDate": new Date(2022, 6, 19).toLocaleDateString("en-US"),
        "endDate": new Date(2022, 7, 17).toLocaleDateString("en-US"),
        "hasTentPlace": true,
        "imageLink": 'Festival_photos/1.jpg',
        "LinkToOffSite": 'https://concert.ua/uk/event/upark',
    },
    {
        "id": '2',
        "title": 'Osocor Winter Residence',
        "description": 'Osocor Winter Residence - це грандіозний проєкт, що готує для вас море неочікуваних та приємних сюрпризів, зустрічі з відомоми героями поттеріани та яскраві фантастичні пригоди.',
        "location": 'Київ, Osocor Residence, Вулиця Виноградна 2',
        "price": "від 350 грн.",
        "startDate": new Date(2021, 11, 4).toLocaleDateString("en-US"),
        "endDate": new Date(2021, 11, 5).toLocaleDateString("en-US"),
        "hasTentPlace": true,
        "imageLink": 'Festival_photos/2.jpg',
        "LinkToOffSite":'https://concert.ua/uk/event/osocor-winter-residence',
    },
    {
        "id": '3',
        "title": 'Thekomakoma',
        "description": 'Thekomakoma це виконавець з Тернопільскої області, який проживає в Києві. Поєднує клубний техно рейв з традиційними українськими танцювальними піснями.',
        "location": 'Lviv, Ukraine',
        "price": "від 250 грн",
        "startDate": new Date(2022, 6, 25).toLocaleDateString("en-US"),
        "endDate": new Date(2022, 6, 28).toLocaleDateString("en-US"),
        "hasTentPlace": true,
        "imageLink": 'Festival_photos/3.jpg',
        "LinkToOffSite":'https://soldout.ua/event/622-thekomakoma?lang=ua',
    },
    {
        "id": '4',
        "title": 'Всеукраїнський щорічний архітектурний конкурс «інтер\'єр року 2021»',
        "description": 'проводиться, щоб визначити найкращі роботи дизайнерів та архітекторів України за допомогою кваліфікованого міжнародного журі.',
        "location": 'КВЦ PARKOVY,Київ, Паркова дорога, 16а',
        "price": 'від 500 грн',
        "startDate": new Date(2021, 11, 3).toLocaleDateString("en-US"),
        "endDate": new Date(2021, 11, 3).toLocaleDateString("en-US"),
        "hasTentPlace": true,
        "imageLink": 'Festival_photos/4.jpg',
        "LinkToOffSite":'https://concert.ua/uk/event/interior-goda-2021',
    },
    {
        "id": '5',
        "title": 'Фестиваль повітряних куль «Монгольф\'єрія»',
        "description": 'Дозволить побачити величезні аеростати, відчуєтеи себе повітроплавцем у прив`язному польоті та отримати позитивні емоції від розважальної програми.',
        "location": 'Lviv, Ukraine',
        "price": '490 грн - дітям до 12 років, 690 грн – дорослим',
        "startDate": new Date(2021, 11, 25).toLocaleDateString("en-US"),
        "endDate": new Date(2021, 11, 25).toLocaleDateString("en-US"),
        "hasTentPlace": true,
        "imageLink": 'Festival_photos/5.jpg',
        "LinkToOffSite":'https://balloonfest.com.ua',
    },
    {
        "id": '6',
        "title": 'KITEN ART TIME',
        "description": 'Міжнародний фестиваль мистецтв',
       "location": 'Китен,Болгарія',
        "price": '230 євро',
        "startDate": new Date(2022, 7, 17).toLocaleDateString("en-US"),
        "endDate": new Date(2022, 7, 17).toLocaleDateString("en-US"),
        "hasTentPlace": true,
        "imageLink": 'Festival_photos/6.jpg',
        "LinkToOffSite":'http://fest-portal.com/ev/kiten-art-time-mezhdunarodnyj-festival-iskusstv/',
    },
    {
        "id": '7',
        "title": 'МІЖНАРОДНИЙ ФЕСТИВАЛІ-КОНКУРС МИСТЕЦТВ «ЗІРКИ ВИХОДЯТЬ НА СЦЕНУ»',
        "description": 'Фестиваль-конкурсу «зірки виходять на сцену»',
        "location": 'вул. Маріїнська, 66 .Скадовськ',
        "price": 'безкоштовно',
        "startDate": new Date(2022, 6, 25).toLocaleDateString("en-US"),
        "endDate": new Date(2022, 6, 28).toLocaleDateString("en-US"),
        "hasTentPlace": true,
        "imageLink": 'Festival_photos/7.jpg',
        "LinkToOffSite":'http://fest-portal.com/ev/mezhdunarodnyj-zvezdy-vyhodyat-na-stsenu-festival-konkurs-iskusstv/',
    },
    {
        "id": '8',
        "title": 'ZAXIDFEST',
        "description": 'Західфест - масштабний музичний фестиваль біля Львова! Неймовірна атмосфера, мальовнича українська природа, драйв, найкращі групи та  привітні люди навколо! ',
        "location": 'село Родатичі',
        "price": 'від 500 грн',
        "startDate": new Date(2022, 6, 25).toLocaleDateString("en-US"),
        "endDate": new Date(2022, 6, 28).toLocaleDateString("en-US"),
        "hasTentPlace": true,
        "imageLink": 'Festival_photos/8.jpg',
        "LinkToOffSite":'https://soldout.ua/event/599-zaxidfest?lang=ua',
    },
    {
        "id": '9',
        "title": 'Фестиваль Файне Місто 2022',
        "description": 'Мешканці Файного Міста це наче окремі світи, які на 5 днів переплетуться між собою і створять одну велику галактику з десятками тисяч  яскравих планет.',
        "location": 'Тернопіль, Іподром',
        "price": 'від 250 грн',
        "startDate": new Date(2022, 7, 28).toLocaleDateString("en-US"),
        "endDate": new Date(2022, 7, 28).toLocaleDateString("en-US"),
        "hasTentPlace": true,/////
        "imageLink": 'Festival_photos/9.jpg',
        "LinkToOffSite":'https://soldout.ua/event/635-festival-faine-misto-2022?lang=ua',
    },
    {
        "id": '10',
        "title": 'BUKOVINA FOLK DANCE',
        "description": 'Відродження та збереження українського фольклору,поєднання народної  та духовної спадщини, показ туристичних можливостей Буковини, як регіону України.',
        "location": 'Чернівці',
        "price": '3500 грн',
        "startDate": new Date(2022, 6, 25).toLocaleDateString("en-US"),
        "endDate": new Date(2022, 6, 28).toLocaleDateString("en-US"),
        "hasTentPlace": true,
        "imageLink": 'Festival_photos/10.jpg',
        "LinkToOffSite":'http://fest-portal.com/ev/bukovina-folk-dance-iii-j-mizhnarodnij-festival-narodnogo-tantsyu/',
    },
    {
        "id": '11',
        "title": 'Міжнародний фестиваль-конкурс мистецтв «GOLD ART FEST»',
        "description": 'Дозволить виявити найбільш талановитих та яскравих виконавців, розкрити творчий потенціал дітей та  зберегти самобутність народної творчості.',
        "location": '',/////////////////////////////////
        "price": '10200грн',
        "startDate": new Date(2022, 4, 28).toLocaleDateString("en-US"),
        "endDate": new Date(2022, 5, 5).toLocaleDateString("en-US"),
        "hasTentPlace": true,
        "imageLink": 'Festival_photos/11.jpg',
        "LinkToOffSite":'http://fest-portal.com/ev/v-mizhnarodnij-festival-konkurs-mistetstv-gold-art-fest-turechchina-z-28kvitnya-po-5-travnya-2022-roku-gotel-armas-kaplan-paradise-5/',
    },
    {
        "id": '12',
        "title": 'Lviv Show Time',
        "description": 'Чесне оцінювання та судійство! Комфортне проживання! Якісне харчування! Дружнє, щире тепле відношення організаторів! Індивідуальний підхід та побудова довгострокової та якісно співпраці! Незабутні емоції!',
        "location": 'проспект В\'ячеслава Чорновола, 2 Львів',
        "price": 'вхід безкоштовний',
        "startDate": new Date(2022, 4, 25).toLocaleDateString("en-US"),
        "endDate": new Date(2022, 4, 27).toLocaleDateString("en-US"),
        "hasTentPlace": true,//
        "imageLink": 'Festival_photos/12.jpg',
        "LinkToOffSite":'http://fest-portal.com/ev/lviv-show-time-25-27-bereznya-2022-r/',
    },
    {
        "id": '13',
        "title": 'Міжнародний конкурс-фестиваль мистецтв «Підкори сцену»',
        "description": 'Дозволяє зберегти національну культуру та розвинути  творчі контакти між колективами та їх керівниками',
        "location": 'Дегтярівська №49-Г Київ',
        "price": '1000 грн',///////
        "startDate": new Date(2022, 2, 5).toLocaleDateString("en-US"),
        "endDate": new Date(2022, 2, 6).toLocaleDateString("en-US"),
        "hasTentPlace": true,///////////////////////////////////
        "imageLink": 'Festival_photos/13.jpg',
        "LinkToOffSite":'http://fest-portal.com/ev/mizhnarodnij-konkurs-festival-mistetstv-pidkori-stsenu-ochna-ta-distantsijna-uchast/',
    },
    {
        "id": '14',
        "title": 'Міжнародний двотуровий багатожанровий фестиваль-конкурс «Рiздвяна зiрка»',
        "description": 'Дозволить познайомитись з кращими солістами та ансамблями, встановити творчі контакти між учасниками та обмінятись досвідом роботи;',
        "location": 'Смт.Івано-Франкове',
        "price": 'безкоштовно',
        "startDate": new Date(2022, 1, 8).toLocaleDateString("en-US"),
        "endDate": new Date(2022, 1, 8).toLocaleDateString("en-US"),
        "hasTentPlace": true,//
        "imageLink": 'Festival_photos/14.jpg',
        "LinkToOffSite":'http://fest-portal.com/ev/mizhnarodnij-dvoturovij-bagatozhanrovij-festival-konkurs-rizdvyana-zirka/',
    },
    {
        "id": '15',
        "title": 'Міжнародний фестиваль-конкурс мистецтв «Новорічне співзвуччя 2021»',
        "description": 'Прилучає населення до національної спадщини різних культур та посилює збереження наступності традицій музичної культури в репертуарі конкурсних колективів;',
        "location": 'Таскалуса, університет штату Алабама',
        "price": '500 грн',
        "startDate": new Date(2021, 12, 31).toLocaleDateString("en-US"),
        "endDate": new Date(2022, 1, 5).toLocaleDateString("en-US"),
        "hasTentPlace": true,///////
        "imageLink": 'Festival_photos/15.jpg',
        "LinkToOffSite":'http://fest-portal.com/ev/mizhnarodnij-festival-konkurs-mistetstv-novorichne-spivzvuchchya-2021-new-year-s-consonance-2021-ladislavoyu-lyubimovoyu/',
    },
    {
        "id": '16',
        "title": 'Всеукраїнський хоровий  фестиваль  різдвяної  музики «VICTORIA»',
        "description": 'Створює пропаганду, підтримку та розвиток вокально-хорового мистецтва та виявлення талановитих виконавців, колективів, викладачів серед учасників.',
        "location": 'вулиця Микільсько-Слобідська, 5,Київ',
        "price": 'гість 300 грн.',
        "startDate": new Date(2022, 12, 27).toLocaleDateString("en-US"),
        "endDate": new Date(2022, 12, 27).toLocaleDateString("en-US"),
        "hasTentPlace": true,//////
        "imageLink": 'Festival_photos/16.jpg',
        "LinkToOffSite":'http://fest-portal.com/ev/iv-vseukrayinskij-horovij-festival-rizdvyanoyi-muziki-victoria/',
    },
    {
        "id": '17',
        "title": 'Всеукраїнський фестиваль-конкурс “Талановитий Я”',
        "description": 'Пропонує нову зручну систему виступів, оцінювання номерів , процедуру нагородження колективів та зміцнює  впевненість в собі і цілеспрямованість до нових досягнень.',
        "location": 'вулиця Біломорська, 1,Київ',
        "price": 'безкоштовно',
        "startDate": new Date(2021, 12, 26).toLocaleDateString("en-US"),
        "endDate": new Date(2021, 12, 26).toLocaleDateString("en-US"),
        "hasTentPlace": true,
        "imageLink": 'Festival_photos/17.jpg',
        "LinkToOffSite":'http://fest-portal.com/ev/vseukrayinskij-festival-konkurs-talanovitij-ya/',
    },
    {
        "id": '18',
        "title": 'Міжнародний фестиваль конкурс мистецтв soloviov art XI',
        "description": 'МІЖНАРОДНИЙ ФЕСТИВАЛЬ який дозволить виявити найкращих вокалістів, солістів та представників театрального мистецтва.',
        "location": 'смт.івано-франкове.',
        "price": '100 грн вхід, 500- участь',
        "startDate": new Date(2021, 12, 25).toLocaleDateString("en-US"),
        "endDate": new Date(2021, 12, 25).toLocaleDateString("en-US"),
        "hasTentPlace": true,
        "imageLink": 'Festival_photos/18.jpg',
        "LinkToOffSite":'http://fest-portal.com/ev/mizhnarodnij-festival-konkurs-mistetstv-soloviov-art-xi/',
    },
    {
        "id": '19',
        "title": '“Super STAR Fest” – креативний міжнародний фестиваль-конкурс талантів',
        "description": 'Креативний тематичний фестиваль-конкурс, на якому учасники не просто змагаються, а ще потрапляють на справжню вечірку в стилі POP-ART',
        "location": 'Україна, Київ - концерт. зала КНУБА',
        "price": '100 грн вхід, 500- участь',
        "startDate": new Date(2021, 12, 25).toLocaleDateString("en-US"),
        "endDate": new Date(2021, 12, 25).toLocaleDateString("en-US"),
        "hasTentPlace": false,
        "imageLink": 'Festival_photos/19.jpg',
        "LinkToOffSite":'http://superstar.org.ua',
    },
    {
        "id": '20',
        "title": 'Міжнародний фестиваль-конкурс талантів',
        "description": 'Дозволяє полинути в дивовижне занурення в фантастично-космічну атмосферу фестивалю SPACE STAR FEST та виявити найкращих зірок серед учасників',
        "location": 'Україна, Київ - концерт. зала КНУБА',
        "price": '500грн',
        "startDate": new Date(2022, 5, 14).toLocaleDateString("en-US"),
        "endDate": new Date(2022, 5, 15).toLocaleDateString("en-US"),
        "hasTentPlace": false,
        "imageLink": 'Festival_photos/20.jpg',
        "LinkToOffSite":'http://spacestar.kiev.ua',
    },
    {
        "id": '21',
        "title": 'Фестиваль-конкурс «Лавина Талантів»',
        "description": 'На цьому фестивалі ви побачите яскраві виступи колективів з особливими талантами, які проходитимуть на сцені з великим екраном. ',
        "location": 'вул. Преображенська, 2,Київ',
        "price": 'безкоштовно',
        "startDate": new Date(2021, 12, 19).toLocaleDateString("en-US"),
        "endDate": new Date(2021, 12, 19).toLocaleDateString("en-US"),
        "hasTentPlace": true,
        "imageLink": 'Festival_photos/24.png',
        "LinkToOffSite":'http://fest-portal.com/ev/festival-konkurs-lavina-talantiv/',
    },
    {
        "id": '22',
        "title": 'Winter Fest',
        "description": 'Чесне оцінювання та судійство! Комфортне проживання! Якісне харчування! Дружнє, щире та тепле відношення організаторів! Індивідуальний підхід та побудова довгострокової та якісної співпраці! Незабутні емоції!',
        "location": 'вул. Лісова, 3, Бояни, Чернівецька',
        "price": '350 грн + проживання',
        "startDate": new Date(2021, 12, 24).toLocaleDateString("en-US"),
        "endDate": new Date(2021, 12, 26).toLocaleDateString("en-US"),
        "hasTentPlace": true,
        "imageLink": 'Festival_photos/21.png',
        "LinkToOffSite":'http://fest-portal.com/ev/winter-fest-24-26-grudnya-2021-r-sonyachna-dolina/',
    },
    {
        "id": '23',
        "title": '«”Різдвяна зірка” 2021» Міжнародний фестиваль-конкурс мистецтв',
        "description": 'Дозволить познайомитись з кращими солістами та ансамблями, встановити творчі контактиміж учасниками та обмінятись досвідом роботи;',
        "location": 'Одеса – Греція',
        "price": 'солісти – 400 грн',
        "startDate": new Date(2021, 12, 23).toLocaleDateString("en-US"),
        "endDate": new Date(2021, 12, 26).toLocaleDateString("en-US"),
        "hasTentPlace": true,////
        "imageLink": 'Festival_photos/22.png',
        "LinkToOffSite":'http://fest-portal.com/ev/rizdvyana-zirka-2021-mizhnarodnij-festival-konkurs-mistetstv-z-ladislava-lyubimova/',
    },
    {
        "id": '24',
        "title": '“СЯЙВО РІЗДВЯНИХ ЗІРОК”до Дня св.Миколая міжнародний фестиваль мистецтв',
        "description": 'міжнародний фестиваль – конкурс  «Зіркафест. Сяйво різдвяних зірок» до Дня св.Миколая',
        "location": 'Київ, вул. Немировича-Данченко 2',
        "price": 'безкоштовно',
        "startDate": new Date(2021, 12, 19).toLocaleDateString("en-US"),
        "endDate": new Date(2021, 12, 19).toLocaleDateString("en-US"),
        "hasTentPlace": true,/////////////////////////////////
        "imageLink": 'Festival_photos/23.png',
        "LinkToOffSite":'http://fest-portal.com/ev/syajvo-rizdvyanih-zirok-do-dnya-sv-mikolaya-mizhnarodnij-festival-mistetstv-m-kiyiv/',
    },
    // {
    //     "id": '25',
    //     "title": '. «Планета Dance Festival» – Всеукраїнський фестиваль-конкурс хореографічних мистецтв',
    //     "description": 'Всеукраїнський фестиваль-конкурс хореографічних мистецтв.',
    //     "location": 'Запоріжжя, ДК Орбіта',
    //     "price": '500 грн.',
    //     "startDate": new Date(2021, 12, 19).toLocaleDateString("en-US"),
    //     "endDate": new Date(2021, 12, 19).toLocaleDateString("en-US"),
    //     "hasTentPlace": true,
    //     "imageLink": 'Festival_photos/25.png',
    //     "LinkToOffSite":'http://fest-portal.com/ev/planeta-dance-festival-vseukrayinskij-festival-konkurs-horeografichnih-mistetstv/',
    // }
];
