export const festivals = [
    {
        "id": '1',
        "title": 'UPark 2022',
        "description": 'UPark Festival - це високий рівень артистів і особлива атмосфера, це глядачі, для яких музика - невід\'ємна частина життя.',
        "location": 'Київ , Sky Family Park ,проспект Ватугіна 2Т',
        "price": 'Від 1649 грн.',
        "startDate": new Date(2022, 6, 19).toLocaleDateString("en-US"),
        "endDate": new Date(2022, 7, 17).toLocaleDateString("en-US"),
        "hasTentPlace": true,
        "imageLink": 'Festival_photos/1.jpg',
        "LinkToOffSite": 'https://concert.ua/uk/event/upark',
    },
    {
        "id": '2',
        "title": 'Osocor Winter Residence',
        "description": 'Osocor Winter Residence - це грандіозний проєкт, що готує для вас море неочікуваних та приємних сюрпризів, зустрічі з відомоми героями поттеріани та яскраві фантастичні пригоди.',
        "location": 'Київ, Osocor Residence, Вулиця Виноградна 2',
        "price": "від 350 грн.",
        "startDate": new Date(2021, 11, 4).toLocaleDateString("en-US"),
        "endDate": new Date(2021, 11, 5).toLocaleDateString("en-US"),
        "hasTentPlace": true,
        "imageLink": 'Festival_photos/2.jpg',
        "LinkToOffSite":'https://concert.ua/uk/event/osocor-winter-residence',
    },
    {
        "id": '3',
        "title": 'Thekomakoma',
        "description": 'Thekomakoma це виконавець з Тернопільскої області, який проживає в Києві. Поєднує клубний техно рейв з традиційними українськими танцювальними піснями.',
        "location": 'Lviv, Ukraine',
        "price": "від 250 грн",
        "startDate": new Date(2022, 6, 25).toLocaleDateString("en-US"),
        "endDate": new Date(2022, 6, 28).toLocaleDateString("en-US"),
        "hasTentPlace": true,
        "imageLink": 'Festival_photos/3.jpg',
        "LinkToOffSite":'https://soldout.ua/event/622-thekomakoma?lang=ua',
    },
    {
        "id": '4',
        "title": 'Всеукраїнський щорічний архітектурний конкурс «інтер\'єр року 2021»',
        "description": 'визначити найкращі роботи дизайнерів та архітекторів України за допомогою кваліфікованого міжнародного журі, а також допомогти дизайнерам та архітекторам продемонструвати ринку свої можливості та зайняти призові місця.',
        "location": 'КВЦ PARKOVY,Київ, Паркова дорога, 16а',
        "price": 'від 500 грн',
        "startDate": new Date(2021, 11, 3).toLocaleDateString("en-US"),
        "endDate": new Date(2021, 11, 3).toLocaleDateString("en-US"),
        "hasTentPlace": true,
        "imageLink": 'Festival_photos/4.jpg',
        "LinkToOffSite":'https://concert.ua/uk/event/interior-goda-2021',
    },
    {
        "id": '5',
        "title": 'Фестиваль повітряних куль «Монгольф\'єрія»',
        "description": 'Фестиваль «Монгольф\'єрія» проходить в Україні з 2009 року у форматі шоу-вистави з прив\'язними або вільними польотами на аеростатах. Ви побачите величезні аеростати, відчуєте себе повітроплавцем у прив\'зному польоті та отримаєте позитивні емоції від розважальної програми.',
       "location": 'Lviv, Ukraine',
        "price": 'ВХІД + ПРИВ\'ЯЗНИЙ ПОЛІТ 490 грн - дітям до 12 років, 690 грн – доросли ВХІД 50 грн - дітям 6 - 12 років, 120 грн - дорослим',
        "startDate": new Date(2021, 11, 25).toLocaleDateString("en-US"),
        "endDate": new Date(2021, 11, 25).toLocaleDateString("en-US"),
        "hasTentPlace": true,
        "imageLink": 'Festival_photos/5.jpg',
        "LinkToOffSite":'https://balloonfest.com.ua',
    },
    {
        "id": '6',
        "title": 'KITEN ART TIME',
        "description": 'Міжнародний фестиваль мистецтв',
       "location": 'Китен,Болгарія',
        "price": '230 євро',
        "startDate": new Date(2022, 7, 17).toLocaleDateString("en-US"),
        "endDate": new Date(2022, 7, 17).toLocaleDateString("en-US"),
        "hasTentPlace": true,
        "imageLink": 'Festival_photos/6.jpg',
        "LinkToOffSite":'http://fest-portal.com/ev/kiten-art-time-mezhdunarodnyj-festival-iskusstv/',
    },
    {
        "id": '7',
        "title": 'МІЖНАРОДНИЙ ФЕСТИВАЛІ-КОНКУРС МИСТЕЦТВ «ЗІРКИ ВИХОДЯТЬ НА СЦЕНУ»',
        "description": 'Фестиваль-конкурсу «зірки виходять на сцену»',
        "location": 'вул. Маріїнська, 66 .Скадовськ',
        "price": 'безкоштовно(оплата за харчування та проживання за власні кошти).toLocaleDateString("en-US")',
        "startDate": new Date(2022, 6, 25).toLocaleDateString("en-US"),
        "endDate": new Date(2022, 6, 28).toLocaleDateString("en-US"),
        "hasTentPlace": true,
        "imageLink": 'Festival_photos/7.jpg',
        "LinkToOffSite":'http://fest-portal.com/ev/mezhdunarodnyj-zvezdy-vyhodyat-na-stsenu-festival-konkurs-iskusstv/',
    },
    {
        "id": '8',
        "title": 'ZAXIDFEST',
        "description": 'Західфест - масштабний музичний фестиваль біля Львова! Неймовірна атмосфера, мальовнича українська природа, драйв, найкращі групи та  привітні люди навколо! ',
        "location": 'село Родатичі',
        "price": 'від 500 грн',
        "startDate": new Date(2022, 6, 25).toLocaleDateString("en-US"),
        "endDate": new Date(2022, 6, 28).toLocaleDateString("en-US"),
        "hasTentPlace": true,
        "imageLink": 'Festival_photos/8.jpg',
        "LinkToOffSite":'https://soldout.ua/event/599-zaxidfest?lang=ua',
    },
    {
        "id": '9',
        "title": 'Фестиваль Файне Місто 2022',
        "description": 'Мешканці Файного Міста це наче окремі світи, які на 5 днів переплетуться між собою і створять одну велику галактику з десятками тисяч  яскравих планет.',
        "location": 'Тернопіль, Іподром',
        "price": 'від 250 грн',
        "startDate": new Date(2022, 7, 28).toLocaleDateString("en-US"),
        "endDate": new Date(2022, 7, 28).toLocaleDateString("en-US"),
        "hasTentPlace": true,/////
        "imageLink": 'Festival_photos/9.jpg',
        "LinkToOffSite":'https://soldout.ua/event/635-festival-faine-misto-2022?lang=ua',
    },
    {
        "id": '10',
        "title": 'BUKOVINA FOLK DANCE',
        "description": 'Відродження та збереження буковинського, українського фольклору, фольклору країн ближнього та далекого зарубіжжя, регіональних традицій і звичаїв, популяризації народного мистецтва, національного колориту, поєднання народної  та духовної спадщини, показу туристичних можливостей Буковини, як регіону України.',
        "location": 'Чернівці',
        "price": '3500 грн(все включено).toLocaleDateString("en-US")',
        "startDate": new Date(2022, 6, 25).toLocaleDateString("en-US"),
        "endDate": new Date(2022, 6, 28).toLocaleDateString("en-US"),
        "hasTentPlace": true,
        "imageLink": 'Festival_photos/10.jpg',
        "LinkToOffSite":'http://fest-portal.com/ev/bukovina-folk-dance-iii-j-mizhnarodnij-festival-narodnogo-tantsyu/',
    },
    {
        "id": '11',
        "title": 'Міжнародний фестиваль-конкурс мистецтв «GOLD ART FEST»',
        "description": 'Міжнародний фестиваль-конкурс організовується с метою виявлення найбільш талановитих та яскравих виконавців, розкриття творчого потенціалу дітей та молоді, збереження самобутньої народної творчості, популяризації різних видів і напрямків творчої діяльності, підвищення професійного рівня  творчих колективів і окремих виконавців, ознайомлення дітей та керівників     з новими тенденціями і напрямками в мистецтві і педагогіці через творчу роботу та майстер-класи, сприяння культурному діалогу дітей різних країн.',
        "location": '',/////////////////////////////////
        "price": '10200грн',
        "startDate": new Date(2022, 4, 28).toLocaleDateString("en-US"),
        "endDate": new Date(2022, 5, 5).toLocaleDateString("en-US"),
        "hasTentPlace": true,
        "imageLink": 'Festival_photos/11.jpg',
        "LinkToOffSite":'http://fest-portal.com/ev/v-mizhnarodnij-festival-konkurs-mistetstv-gold-art-fest-turechchina-z-28kvitnya-po-5-travnya-2022-roku-gotel-armas-kaplan-paradise-5/',
    },
    {
        "id": '12',
        "title": 'Lviv Show Time',
        "description": 'Чесне оцінювання та судійство! Комфортне проживання! Якісне харчування! Дружнє, щире тепле відношення організаторів! Індивідуальний підхід та побудова довгострокової та якісно співпраці! Незабутні емоції!',
        "location": 'проспект В\'ячеслава Чорновола, 2 Львів',
        "price": 'вхід безкоштовний',
        "startDate": new Date(2022, 4, 25).toLocaleDateString("en-US"),
        "endDate": new Date(2022, 4, 27).toLocaleDateString("en-US"),
        "hasTentPlace": true,//
        "imageLink": 'Festival_photos/12.jpg',
        "LinkToOffSite":'http://fest-portal.com/ev/lviv-show-time-25-27-bereznya-2022-r/',
    },
    {
        "id": '13',
        "title": 'Міжнародний конкурс-фестиваль мистецтв «Підкори сцену»',
        "description": 'збереження і пропаганда національних культур, розвиток творчих контактів між колективами та їх керівниками, зміцнення міжнародних зв’язків між колективами та окремими виконавцями країн-учасниць, підвищення виконавської майстерності колективів і окремих виконавців',
        "location": 'Дегтярівська №49-Г Київ',
        "price": '',///////
        "startDate": new Date(2022, 2, 5).toLocaleDateString("en-US"),
        "endDate": new Date(2022, 2, 6).toLocaleDateString("en-US"),
        "hasTentPlace": true,///////////////////////////////////
        "imageLink": 'Festival_photos/13.jpg',
        "LinkToOffSite":'http://fest-portal.com/ev/mizhnarodnij-konkurs-festival-mistetstv-pidkori-stsenu-ochna-ta-distantsijna-uchast/',
    },
    {
        "id": '14',
        "title": 'Міжнародний двотуровий багатожанровий фестиваль-конкурс «Рiздвяна зiрка»',
        "description": 'Основні напрямки та цілі ВБФ «Злагода» це благодійна діяльність в сфері соціального захисту населення, надання безпосередньої допомоги власною працею членами ВБФ «Злагода» і передача результатів власної творчої діяльності, допомога дитячим будинкам та інтернатам.',
        "location": 'Смт.Івано-Франкове',
        "price": 'безкоштовно',
        "startDate": new Date(2022, 1, 8).toLocaleDateString("en-US"),
        "endDate": new Date(2022, 1, 8).toLocaleDateString("en-US"),
        "hasTentPlace": true,//
        "imageLink": 'Festival_photos/14.jpg',
        "LinkToOffSite":'http://fest-portal.com/ev/mizhnarodnij-dvoturovij-bagatozhanrovij-festival-konkurs-rizdvyana-zirka/',
    },
    {
        "id": '15',
        "title": 'Міжнародний фестиваль-конкурс мистецтв «Новорічне співзвуччя 2021»',
        "description": 'Bідродження, збереження і розвиток національних культур. Знайомство з кращими солістами та ансамблями, встановлення творчих контактів між учасниками, обмін досвідом роботи.Прилучення населення до національної спадщини різних культур. Збереження наступності традицій музичної, театральної та хореографічної культури в репертуарі конкурсних колективів;',
        "location": 'Таскалуса, університет штату Алабама',
        "price": 'солісти – 400 грн;інструменталісти соло – 250 грн;Дуети – 250 грн. з одного учасника',
        "startDate": new Date(2021, 12, 31).toLocaleDateString("en-US"),
        "endDate": new Date(2022, 1, 5).toLocaleDateString("en-US"),
        "hasTentPlace": true,///////
        "imageLink": 'Festival_photos/15.jpg',
        "LinkToOffSite":'http://fest-portal.com/ev/mizhnarodnij-festival-konkurs-mistetstv-novorichne-spivzvuchchya-2021-new-year-s-consonance-2021-ladislavoyu-lyubimovoyu/',
    },
    {
        "id": '16',
        "title": 'Всеукраїнський хоровий  фестиваль  різдвяної  музики «VICTORIA»',
        "description": 'знайомство учасників фестивалю  та   гостей (слухачів).toLocaleDateString("en-US")  з цікавим  та сучасним  музичним різдвяним  репертуаром;пропаганда, підтримка та розвиток вокально-хорового мистецтва  виявлення талановитих виконавців, колективів, викладачів серед учасників фестивалю  та   стимулювання їх творчої активності; виховання у підростаючого покоління розуміння та любові до світового мистецтва, духовної культури як основи у формуванні світогляду;',
        "location": 'вулиця Микільсько-Слобідська, 5,Київ',
        "price": ': 4000 грн. з  хорового колективу та 3000 грн.  з ансамблю, гість 300 грн.',
        "startDate": new Date(2022, 12, 27).toLocaleDateString("en-US"),
        "endDate": new Date(2022, 12, 27).toLocaleDateString("en-US"),
        "hasTentPlace": true,//////
        "imageLink": 'Festival_photos/16.jpg',
        "LinkToOffSite":'http://fest-portal.com/ev/iv-vseukrayinskij-horovij-festival-rizdvyanoyi-muziki-victoria/',
    },
    {
        "id": '17',
        "title": 'Всеукраїнський фестиваль-конкурс “Талановитий Я”',
        "description": ' цінності нашого фестивалю: У нас немає тих, хто програв. У нас ексклюзивні нагороди, розроблені спеціально для даного фестивалю. Безкоштовні фото і відео матеріали для всіх учасників. Безкоштовна он-лайн трансляція всього фестивалю в режимі реального часу. Виступи колективів проходять на сцені  з великим екраном, на якому можна розмістити емблему колективу або заставку під конкретний танок. Подарунки від спонсорів. Кращі учасники отримують Гран-Прі та Особливі відзнаки.',
        "location": 'вулиця Біломорська, 1,Київ',
        "price": 'безкоштовно',
        "startDate": new Date(2021, 12, 26).toLocaleDateString("en-US"),
        "endDate": new Date(2021, 12, 26).toLocaleDateString("en-US"),
        "hasTentPlace": true,
        "imageLink": 'Festival_photos/17.jpg',
        "LinkToOffSite":'http://fest-portal.com/ev/vseukrayinskij-festival-konkurs-talanovitij-ya/',
    },
    {
        "id": '18',
        "title": 'Міжнародний фестиваль конкурс мистецтв soloviov art XI',
        "description": 'МІЖНАРОДНИЙ ФЕСТИВАЛЬ КОНКУРС МИСТЕЦТВ Кожен учасник представляє один твір в одній віковій категорії. Забороняється виконувати вульгарні тексти.',
        "location": 'смт.івано-франкове.',
        "price": 'Для індивідуальних учасників: вокал, інструментальне мистецтво, художнє слово – 500 грн; Для дуетів – 400 грн. з кожного учасника; Тріо, квартетів – 350 грн з кожного учасника; Для колективів малих форм (до 6 учасників).toLocaleDateString("en-US") – 300 грн. з кожного учасника; Для ансамблів від 7 і більше – 250 грн. з кожного учасника.',
        "startDate": new Date(2021, 12, 25).toLocaleDateString("en-US"),
        "endDate": new Date(2021, 12, 25).toLocaleDateString("en-US"),
        "hasTentPlace": true,
        "imageLink": 'Festival_photos/18.jpg',
        "LinkToOffSite":'http://fest-portal.com/ev/mizhnarodnij-festival-konkurs-mistetstv-soloviov-art-xi/',
    },
    {
        "id": '19',
        "title": '“Super STAR Fest” – креативний міжнародний фестиваль-конкурс талантів',
        "description": 'Креативний тематичний фестиваль-конкурс, на якому учасники не просто змагаються, а ще потрапляють на справжню вечірку в стилі POP-ART',
        "location": 'Україна, Київ - концерт. зала КНУБА',
        "price": '100 грн вхід, 500- участь',
        "startDate": new Date(2021, 12, 25).toLocaleDateString("en-US"),
        "endDate": new Date(2021, 12, 25).toLocaleDateString("en-US"),
        "hasTentPlace": false,
        "imageLink": 'Festival_photos/19.jpg',
        "LinkToOffSite":'http://superstar.org.ua',
    },
    {
        "id": '20',
        "title": 'Міжнародний фестиваль-конкурс талантів',
        "description": 'дивовижне занурення в фантастично-космічну атмосферу фестивалю SPACE STAR FEST. Круті space фотозони 2.7 * 6м, 2.5 * 4м з червоною доріжкою, і ще 3 міні-локації з перформансом. Космічний ведучий з конкурсами, сюрпризами, космічними подарунками та космічної дискотекою! Медійний, професійний і сучасний склад журі (відомі Артисти шоу-бізнесу).toLocaleDateString("en-US"). Зоряні селфі, відео та Автограф сесії з відомими людьми шоу-індустрії. Турботливі Хостес-помічники які проведуть Вас в кімнати-гримерки для підготовки до виступу',
        "location": 'Україна, Київ - концерт. зала КНУБА',
        "price": '500грн',
        "startDate": new Date(2022, 5, 14).toLocaleDateString("en-US"),
        "endDate": new Date(2022, 5, 15).toLocaleDateString("en-US"),
        "hasTentPlace": false,
        "imageLink": 'Festival_photos/20.jpg',
        "LinkToOffSite":'http://spacestar.kiev.ua',
    },
    {
        "id": '21',
        "title": 'Фестиваль-конкурс «Лавина Талантів»',
        "description": 'Ексклюзивні нагороди, розроблені спеціально під кожний фестиваль. Безкоштовні фото и відео матеріали для всіх учасников. Безкоштовна он-лайн трансляція всього фестивалю в режимі реального часу. Виступи колективів проходять на сцені з великим екраном, на якому розміщена назва колективу під час виступу. Подарунки від спонсорів.',
        "location": 'вул. Преображенська, 2,Київ',
        "price": 'безкоштовно',
        "startDate": new Date(2021, 12, 19).toLocaleDateString("en-US"),
        "endDate": new Date(2021, 12, 19).toLocaleDateString("en-US"),
        "hasTentPlace": true,
        "imageLink": 'Festival_photos/24.png',
        "LinkToOffSite":'http://fest-portal.com/ev/festival-konkurs-lavina-talantiv/',
    },
    {
        "id": '22',
        "title": 'Winter Fest',
        "description": 'Чесне оцінювання та судійство! Комфортне проживання! Якісне харчування! Дружнє, щире та тепле відношення організаторів! Індивідуальний підхід та побудова довгострокової та якісної співпраці! Незабутні емоції!',
        "location": 'вул. Лісова, 3, Бояни, Чернівецька',
        "price": '350 грн + проживання',
        "startDate": new Date(2021, 12, 24).toLocaleDateString("en-US"),
        "endDate": new Date(2021, 12, 26).toLocaleDateString("en-US"),
        "hasTentPlace": true,
        "imageLink": 'Festival_photos/21.png',
        "LinkToOffSite":'http://fest-portal.com/ev/winter-fest-24-26-grudnya-2021-r-sonyachna-dolina/',
    },
    {
        "id": '23',
        "title": '«”Різдвяна зірка” 2021» Міжнародний фестиваль-конкурс мистецтв',
        "description": 'Відродження, збереження і розвиток національних культур; Знайомство з кращими солістами та ансамблями, встановлення творчих контактів між учасниками, обмін досвідом роботи; Прилучення населення до національної спадщини різних культур. Збереження наступності традицій музичної, театральної та хореографічної культури в репертуарі конкурсних колективів.',
        "location": 'Одеса – Чорноморськ – Греція',
        "price": 'солісти – 400 грн. дуети – 500 гр колективи від 3-х до 5 осіб. – 200 грн. з учасника',
        "startDate": new Date(2021, 12, 23).toLocaleDateString("en-US"),
        "endDate": new Date(2021, 12, 26).toLocaleDateString("en-US"),
        "hasTentPlace": true,////
        "imageLink": 'Festival_photos/22.png',
        "LinkToOffSite":'http://fest-portal.com/ev/rizdvyana-zirka-2021-mizhnarodnij-festival-konkurs-mistetstv-z-ladislava-lyubimova/',
    },
    {
        "id": '24',
        "title": '“СЯЙВО РІЗДВЯНИХ ЗІРОК”до Дня св.Миколая міжнародний фестиваль мистецтв',
        "description": 'міжнародний фестиваль – конкурс  «Зіркафест. Сяйво різдвяних зірок» до Дня св.Миколая',
        "location": 'Київ, вул. Немировича-Данченко 2',
        "price": 'безкоштовно',
        "startDate": new Date(2021, 12, 19).toLocaleDateString("en-US"),
        "endDate": new Date(2021, 12, 19).toLocaleDateString("en-US"),
        "hasTentPlace": true,/////////////////////////////////
        "imageLink": 'Festival_photos/23.png',
        "LinkToOffSite":'http://fest-portal.com/ev/syajvo-rizdvyanih-zirok-do-dnya-sv-mikolaya-mizhnarodnij-festival-mistetstv-m-kiyiv/',
    },
    // {
    //     "id": '25',
    //     "title": '. «Планета Dance Festival» – Всеукраїнський фестиваль-конкурс хореографічних мистецтв',
    //     "description": 'Всеукраїнський фестиваль-конкурс хореографічних мистецтв.',
    //     "location": 'Запоріжжя, ДК Орбіта',
    //     "price": '500 грн.',
    //     "startDate": new Date(2021, 12, 19).toLocaleDateString("en-US"),
    //     "endDate": new Date(2021, 12, 19).toLocaleDateString("en-US"),
    //     "hasTentPlace": true,
    //     "imageLink": 'Festival_photos/25.png',
    //     "LinkToOffSite":'http://fest-portal.com/ev/planeta-dance-festival-vseukrayinskij-festival-konkurs-horeografichnih-mistetstv/',
    // }
];
